<?php

/**
 * @file Flag limit module
 *
 * Limits the number of flagged items at any time to X.
 *
 * Intended for the following use case: A specified number of flagged 
 * items needs to appear in a rotator at the top of a page.  When a new
 * item is marked as flagged, the oldest item marked as flagged needs to
 * move from the rotator, into a list of unflagged content below.
 */
 

/**
 * Implementation of hook_flag(). Trigger actions if any are available.
 */
function flag_Limit_flag($action, $flag, $content_id, $account) {
  $limited = \Drupal::state()->get('flag_limit_' . $flag->name, FALSE);
  if ($action == 'flag' && $limited) {
    
    // Get the flag limit.
    $limit = \Drupal::state()->get('flag_limit_' . $flag->name . '_value', NULL);
    
    // Get all the current flags.
    $query = "SELECT * FROM {flag_content} WHERE fid = %d AND (uid = %d OR uid = 0) ORDER BY timestamp DESC";  
    $result = db_query($query, $flag->fid, $account->uid);
    $i = 1;
    while ($row = db_fetch_object($result)) {
      if ($i++ > $limit) {
        flag('unflag', $flag->name, $row->content_id, $account);
      }
    }
      
  }
}

